spring.application.name=apigateway

server.port=9000

#Product Service
spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:9010
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/products/**

#Order Service
spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:9020
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/orderservice/**

#Payment Service
spring.cloud.gateway.server.webmvc.routes[2].id=payment-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:9030
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/payments/**


# ? Gateway fetches public key from auth server to validate JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9001

spring.datasource.url=jdbc:mysql://localhost:3306/authservice
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

security.authorization.enabled=false