
# sampling only — no management.tracing.enabled needed
management.tracing.sampling.probability=1.0



# correct loggers for MVC gateway (not reactive)
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
logging.level.io.micrometer.tracing=DEBUG
