server.port=0

# Circuit Breaker
resilience4j.circuitbreaker.instances.paymentservice.slidingWindowSize=5
resilience4j.circuitbreaker.instances.paymentservice.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentservice.waitDurationInOpenState=10s

# Retry
resilience4j.retry.instances.paymentservice.maxAttempts=3
resilience4j.retry.instances.paymentservice.waitDuration=1s

# TimeLimiter (Timeout)
resilience4j.timelimiter.instances.paymentservice.timeoutDuration=3s
