spring.application.name=config-server

server.port=8888

spring.cloud.config.server.git.uri=https://github.com/RazibHossain/Spring-Boot.git
spring.cloud.config.server.git.search-paths=Demo-Microservice-with-Spring-Boot-3/central-configuration-files
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.clone-on-start=true
