spring.application.name=config-server

server.port=8888

spring.cloud.config.server.git.uri=https://github.com/RazibHossain/Spring-Boot.git
spring.cloud.config.server.git.search-paths=Smart Logistics and Order Management System/central-configuration
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=master

#See properties file from browser
#http://localhost:8888/application/default
#http://localhost:8888/product-service/dev

spring.security.user.name=configuser
spring.security.user.password=configpass